[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
community_engagement_protocol = "7FQ74JMt2Eeca2RD2aLVBv4No8e9PUt8SHfGsUzKhqje"

[programs.devnet]
community_engagement_protocol = "7FQ74JMt2Eeca2RD2aLVBv4No8e9PUt8SHfGsUzKhqje"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "Localnet"
# wallet = "~/.config/solana/id.json"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
